stages:
  - test
  - deploy
  
Test:
  stage: test
  script:
    - cat README.md
    - echo "$CI_JOB_ID" > _job_id

Deploy:
  image: byrnedo/alpine-curl
  stage: deploy
  variables:
    REF_NAME: $CI_COMMIT_REF_NAME
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master http://gitlab.loc/api/v4/projects/1111/trigger/pipeline
